
import "../styles/globals.css";

import { Cairo } from "next/font/google";
import Navbar from "@/_components/layout/navbar"
import Hero from "@/_components/layout/hero";
import LatestNews from "@/_components/layout/latestNews";
import About from "@/_components/layout/aboutus";
import Specializations from "@/_components/layout/home_specializations";
const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["400", "500", "700"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${cairo.className}  text-base-content font-sans `}
      >
        <Navbar/>
        <Hero />
        <div className="w-[85%] mx-auto "> 
        <LatestNews />
        <Specializations />
        <About />
         </div>
        
        {children}
      </body>
    </html>
  );
}
