
import "../styles/globals.css";
import { Cairo } from "next/font/google";


const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["400", "500", "700"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${cairo.className} bg-base-100 text-base-content font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
